export const settingsModel = {
  theme: 'system',
  enabledServices: {
    github: true,
    stackOverflow: true,
    internalStackOverflow: false,
  },
  queryDefaults: {
    numberOfDaysToQuery: 1,
    startHour: 10,
  },
  useTestData: false,
  isVerbose: false,
  timestamp: {
    lastRun: null,
    previousRun: null,
  },
  runInDebugMode: false,
  azureDevOps: {
    org: '',
    project: '',
    apiVersion: '6.1',
  },
  github: {
    apiUrl: 'https://api.github.com/graphql',
  },
  repositories: {
    github: [
      { org: 'Microsoft', repo: 'botbuilder-azure', enabled: false },
      { org: 'Microsoft', repo: 'botbuilder-cognitiveservices', enabled: false },
      { org: 'Microsoft', repo: 'botbuilder-dotnet', enabled: false },
      { org: 'Microsoft', repo: 'botbuilder-java', enabled: false },
      { org: 'Microsoft', repo: 'botbuilder-js', enabled: false },
      { org: 'Microsoft', repo: 'botbuilder-python', enabled: false },
      { org: 'Microsoft', repo: 'botbuilder-samples', enabled: false },
      { org: 'Microsoft', repo: 'agents', enabled: true },
      { org: 'Microsoft', repo: 'agents-for-net', enabled: true },
      { org: 'Microsoft', repo: 'agents-for-js', enabled: true },
      { org: 'Microsoft', repo: 'agents-for-python', enabled: true },
      { org: 'Microsoft', repo: 'botbuilder-tools', enabled: false },
      { org: 'Microsoft', repo: 'botbuilder-v3', enabled: false },
      { org: 'Microsoft', repo: 'botframework-cli', enabled: false },
      { org: 'Microsoft', repo: 'botframework-composer', enabled: false },
      { org: 'Microsoft', repo: 'botframework-emulator', enabled: false },
      { org: 'Microsoft', repo: 'botframework-directlinejs', enabled: false },
      { org: 'Microsoft', repo: 'botframework-solutions', enabled: false, labels: ['support'] },
      { org: 'Microsoft', repo: 'botframework-services', enabled: false },
      { org: 'Microsoft', repo: 'botframework-sdk', enabled: false, ignoreLabels: ['TeamsSDK'] },
      { org: 'Microsoft', repo: 'botframework-webchat', enabled: false },
      { org: 'MicrosoftDocs', repo: 'bot-docs', enabled: false, labels: ['team: support'] },
    ],
    stackOverflow: [
      { tag: 'adaptive-cards', enabled: true },
      { tag: 'azure-bot-service', enabled: true },
      { tag: 'botframework', enabled: true },
      { tag: 'direct-line-botframework', enabled: true },
      { tag: 'luis', enabled: false },
      { tag: 'azure-language-understanding', enabled: true },
      { tag: 'qnamaker', enabled: false },
      { tag: 'web-chat', enabled: true },
      { tag: 'microsoft-agent', enabled: true },
      { tag: 'teams-ai', enabled: true },
      { tag: 'azure-agent', enabled: true },
      { tag: 'microsoft-copilot', enabled: true },
      { tag: 'copilot-for-m365', enabled: true },
      { tag: 'teams-toolkit', enabled: true },
    ],
    internalStackOverflow: [
      { tag: 'azure-bot-service', enabled: true },
      { tag: 'bot', enabled: true },
      { tag: 'bot-framework', enabled: true },
      { tag: 'luis.ai', enabled: true },
    ],
  },
};
